In [2]:
%pwd

'C:\\cakd7\\github\\데이터안심구역_팀\\teamproject'

# 2021-12

In [38]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
stay_df = pd.read_excel('staypop202112.xlsx', header=None)
#정렬
stay_df=stay_df.rename(columns = {0:'행정기관코드',1:'행정기관', 2:'총인구수', 3:'세대수', 4:'세대당 인구', 5:'남자 인구수', 6:'여자 인구수', 7:'남여 비율'})
stay_df.drop([0,1,2,3],inplace=True)
stay_df.reset_index(drop=True,inplace=True)
stay_df.head()

,행정기관코드,행정기관,총인구수,세대수,세대당 인구,남자 인구수,여자 인구수,남여 비율
0,1111000000,서울특별시 종로구,"144,683","73,494",1.97,"70,183","74,500",0.94
1,1114000000,서울특별시 중구,"122,499","63,519",1.93,"59,630","62,869",0.95
2,1117000000,서울특별시 용산구,"222,953","111,036",2.01,"107,210","115,743",0.93
3,1120000000,서울특별시 성동구,"285,990","134,233",2.13,"139,380","146,610",0.95
4,1121500000,서울특별시 광진구,"339,996","167,949",2.02,"164,058","175,938",0.93

## 필요컬럼 추가

- 시군구명

In [42]:
import re
for i in range(len(stay_df)):
    name = re.search('\s{1}(\w+구)',stay_df.loc[i,'행정기관']).group(1)
    stay_df.loc[i,'시군구명'] = name
#     print(name)
stay_df.head()

,행정기관코드,행정기관,총인구수,세대수,세대당 인구,남자 인구수,여자 인구수,남여 비율,시군구명
0,1111000000,서울특별시 종로구,"144,683","73,494",1.97,"70,183","74,500",0.94,종로구
1,1114000000,서울특별시 중구,"122,499","63,519",1.93,"59,630","62,869",0.95,중구
2,1117000000,서울특별시 용산구,"222,953","111,036",2.01,"107,210","115,743",0.93,용산구
3,1120000000,서울특별시 성동구,"285,990","134,233",2.13,"139,380","146,610",0.95,성동구
4,1121500000,서울특별시 광진구,"339,996","167,949",2.02,"164,058","175,938",0.93,광진구

- 일자

In [46]:
stay_df['year'] = 2021
stay_df['month'] = 12
stay_df.head()
stay_df.columns

Index(['행정기관코드', '행정기관', '총인구수', '세대수', '세대당 인구', '남자 인구수', '여자 인구수', '남여 비율',
       '시군구명', 'year', 'month'],
      dtype='object')

- 컬럼순서

In [48]:
stay_df = stay_df.reindex(columns=['year', 'month','행정기관코드', '행정기관','시군구명', '총인구수', '세대수', '세대당 인구', '남자 인구수', '여자 인구수', '남여 비율'])
stay_df.head()

,year,month,행정기관코드,행정기관,시군구명,총인구수,세대수,세대당 인구,남자 인구수,여자 인구수,남여 비율
0,2021,12,1111000000,서울특별시 종로구,종로구,"144,683","73,494",1.97,"70,183","74,500",0.94
1,2021,12,1114000000,서울특별시 중구,중구,"122,499","63,519",1.93,"59,630","62,869",0.95
2,2021,12,1117000000,서울특별시 용산구,용산구,"222,953","111,036",2.01,"107,210","115,743",0.93
3,2021,12,1120000000,서울특별시 성동구,성동구,"285,990","134,233",2.13,"139,380","146,610",0.95
4,2021,12,1121500000,서울특별시 광진구,광진구,"339,996","167,949",2.02,"164,058","175,938",0.93

## 파일저장

In [54]:
stay_df.to_excel('restaypop202112.xlsx',index=False)

# 구 별 주거인구 sort

In [50]:
stay_df.sort_values(by='총인구수', ascending=False)

,year,month,행정기관코드,행정기관,시군구명,총인구수,세대수,세대당 인구,남자 인구수,여자 인구수,남여 비율
23,2021,12,1171000000,서울특별시 송파구,송파구,"658,338","282,417",2.33,"317,346","340,992",0.93
15,2021,12,1150000000,서울특별시 강서구,강서구,"574,315","271,175",2.12,"276,292","298,023",0.93
22,2021,12,1168000000,서울특별시 강남구,강남구,"533,042","234,233",2.28,"255,047","277,995",0.92
10,2021,12,1135000000,서울특별시 노원구,노원구,"510,956","217,378",2.35,"246,053","264,903",0.93
20,2021,12,1162000000,서울특별시 관악구,관악구,"485,699","276,597",1.76,"243,991","241,708",1.01
11,2021,12,1138000000,서울특별시 은평구,은평구,"473,307","214,711",2.20,"226,458","246,849",0.92
24,2021,12,1174000000,서울특별시 강동구,강동구,"462,664","201,613",2.29,"227,002","235,662",0.96
14,2021,12,1147000000,서울특별시 양천구,양천구,"447,302","181,404",2.47,"219,214","228,088",0.96
7,2021,12,1129000000,서울특별시 성북구,성북구,"430,528","195,017",2.21,"207,578","222,950",0.93
21,2021,12,1165000000,서울특별시 서초구,서초구,"412,279","170,244",2.42,"197,034","215,245",0.92
16,2021,12,1153000000,서울특별시 구로구,구로구,"396,754","180,929",2.19,"195,537","201,217",0.97
6,2021,12,1126000000,서울특별시 중랑구,중랑구,"387,350","185,712",2.09,"191,112","196,238",0.97
19,2021,12,1159000000,서울특별시 동작구,동작구,"385,483","184,812",2.09,"186,426","199,057",0.94
18,2021,12,1156000000,서울특별시 영등포구,영등포구,"376,837","187,020",2.01,"185,926","190,911",0.97
13,2021,12,1144000000,서울특별시 마포구,마포구,"368,905","179,861",2.05,"173,504","195,401",0.89
4,2021,12,1121500000,서울특별시 광진구,광진구,"339,996","167,949",2.02,"164,058","175,938",0.93
5,2021,12,1123000000,서울특별시 동대문구,동대문구,"337,400","168,219",2.01,"166,646","170,754",0.98
9,2021,12,1132000000,서울특별시 도봉구,도봉구,"317,366","138,656",2.29,"154,487","162,879",0.95
12,2021,12,1141000000,서울특별시 서대문구,서대문구,"304,819","143,647",2.12,"145,694","159,125",0.92
8,2021,12,1130500000,서울특별시 강북구,강북구,"299,182","144,536",2.07,"145,705","153,477",0.95
3,2021,12,1120000000,서울특별시 성동구,성동구,"285,990","134,233",2.13,"139,380","146,610",0.95
17,2021,12,1154500000,서울특별시 금천구,금천구,"230,811","117,595",1.96,"116,527","114,284",1.02
2,2021,12,1117000000,서울특별시 용산구,용산구,"222,953","111,036",2.01,"107,210","115,743",0.93
0,2021,12,1111000000,서울특별시 종로구,종로구,"144,683","73,494",1.97,"70,183","74,500",0.94
1,2021,12,1114000000,서울특별시 중구,중구,"122,499","63,519",1.93,"59,630","62,869",0.95