# <20, 21년 전기차 신규등록 (소유 파악) - 종속변수>

In [142]:
import pandas as pd
import json
import warnings
warnings.filterwarnings('ignore')

In [143]:
data = pd.read_excel("자치구별 연료별 자동차 등록현황.xlsx")
# 20_21년 자치구별 연료별 자동차 등록현황(서울열린데이터광장)
data.head()

,2015년 ~ 2021년도 12월말 기준 시군구별 용도별 차종별 연료별 등록 현황,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,연월,사용본거지시군구,시군구코드,용도,차종종별,연료,건수
1,202012,서울특별시 종로구,11110,관용,승용,휘발유,155
2,202012,서울특별시 종로구,11110,관용,화물,경유,330
3,202012,서울특별시 종로구,11110,관용,화물,기타연료,3
4,202012,서울특별시 종로구,11110,관용,특수,기타연료,2

## 1. 컬럼 값 확인 및 정리

## 1-1) 컬럼 정리

In [144]:
# 컬럼명 변경
data = data.drop(index=0, axis=0)
data.columns = ['등록연도', '사용본거지', '시군구코드', '용도', '차종종별', '연료', '건수']
data.head()

     등록연도      사용본거지  시군구코드   용도 차종종별    연료   건수
1  202012  서울특별시 종로구  11110   관용   승용   휘발유  155
2  202012  서울특별시 종로구  11110   관용   화물    경유  330
3  202012  서울특별시 종로구  11110   관용   화물  기타연료    3
4  202012  서울특별시 종로구  11110   관용   특수  기타연료    2
5  202012  서울특별시 종로구  11110  자가용   화물   휘발유   71

In [145]:
# 등록연도 값 정리 (년도만 출력)
for i in range(3077):
    data.iloc[i, 0] = int(data.iloc[i, 0][:4])
    
data['등록연도']

1       2020
2       2020
3       2020
4       2020
5       2020
        ...
3073    2021
3074    2021
3075    2021
3076    2021
3077    2021
Name: 등록연도, Length: 3077, dtype: object

In [146]:
# 사용본거지 변경 (서울특별시 제거)
data['사용본거지'] = data['사용본거지'].str.replace('서울특별시 ', '')
data

      등록연도 사용본거지  시군구코드   용도 차종종별       연료   건수
1     2020   종로구  11110   관용   승용      휘발유  155
2     2020   종로구  11110   관용   화물       경유  330
3     2020   종로구  11110   관용   화물     기타연료    3
4     2020   종로구  11110   관용   특수     기타연료    2
5     2020   종로구  11110  자가용   화물      휘발유   71
...    ...   ...    ...  ...  ...      ...  ...
3073  2021   송파구  11710  영업용   승용       수소    2
3074  2021   송파구  11710  영업용   승합  휘발유(무연)    1
3075  2021   강동구  11740  자가용   승합     기타연료   70
3076  2021   강동구  11740  자가용   특수     기타연료   27
3077  2021   강동구  11740  영업용   승합      엘피지  179

[3077 rows x 7 columns]

## 1-2) 컬럼 값 확인

In [147]:
## 값 확인하기
print("****null값****", '\n', data.isnull().sum(), '\n')
print("****info값****", '\n', data.info(), '\n')
print("****사용본거지****", '\n', data['사용본거지'].value_counts(), '\n')
print("****시군구코드****", '\n', data['시군구코드'].value_counts(), '\n')
print("****용도****", '\n', data['용도'].value_counts(), '\n')
print("****차종종별", '\n', data['차종종별'].value_counts(),'\n')
print("****연료", '\n', data["연료"].value_counts())

****null값****
 등록연도     0
사용본거지    0
시군구코드    0
용도       0
차종종별     0
연료       0
건수       0
dtype: int64

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3077 entries, 1 to 3077
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   등록연도    3077 non-null   object
 1   사용본거지   3077 non-null   object
 2   시군구코드   3077 non-null   object
 3   용도      3077 non-null   object
 4   차종종별    3077 non-null   object
 5   연료      3077 non-null   object
 6   건수      3077 non-null   object
dtypes: object(7)
memory usage: 168.4+ KB
****info값****
 None

****사용본거지****
 서초구     136
성동구     134
송파구     132
영등포구    132
강서구     131
강남구     130
종로구     127
마포구     127
중구      125
서대문구    123
도봉구     123
은평구     122
양천구     122
중랑구     121
광진구     121
노원구     120
구로구     119
금천구     119
강동구     119
동대문구    118
강북구     117
성북구     117
관악구     115
용산구     115
동작구     112
Name: 사용본거지, dtype: int64

****시군구코드****
 11650    136
11200    134
11710    132
11560    132
11500    131
11680    130
11110    127
11440    127
11140    125
11410    123
11320    123
11380    122
11470    122
11260    121
11215    121
11350    120
11530    119
11545    119
11740    119
11230    118
11305    117
11290    117
11620    115
11170    115
11590    112
Name: 시군구코드, dtype: int64

****용도****
 자가용    1399
영업용     866
관용      812
Name: 용도, dtype: int64

****차종종별
 승용    1336
화물     764
승합     663
특수     314
Name: 차종종별, dtype: int64

****연료
 경유               600
엘피지              479
전기               360
기타연료             294
휘발유(무연)          282
휘발유              281
CNG              260
하이브리드(휘발유+전기)    153
하이브리드(LPG+전기)    112
수소               107
하이브리드(경유+전기)      80
휘발유(유연)           55
하이브리드(CNG+전기)     14
Name: 연료, dtype: int64

In [148]:
# 문자를 숫자를 변경
data['건수'] = data['건수'].astype(int)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3077 entries, 1 to 3077
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   등록연도    3077 non-null   object
 1   사용본거지   3077 non-null   object
 2   시군구코드   3077 non-null   object
 3   용도      3077 non-null   object
 4   차종종별    3077 non-null   object
 5   연료      3077 non-null   object
 6   건수      3077 non-null   int32
dtypes: int32(1), object(6)
memory usage: 156.4+ KB

## 1-3) 문자 변경 (LabelEncoder)

In [149]:
# # 문자 값 변경 방법: 인코딩 -LabelEncoder
# #각 값 객체의 개수에 따라 입력해서 바꿔줌(0, 1 로 2개면 2개, 1,2,3으로 3개면 3개)
# from sklearn.preprocessing import LabelEncoder

# le = LabelEncoder() #객체를 만들어줌
# features = ['차종종별', '용도'] #바꿀 열 따로  뽑아줌(for 문 사용하기 위해)
# for f in features:
#     data[f] = le.fit_transform(data[f])  #fit _ transform
# data.head()

In [150]:
# print(data['차종종별'].value_counts(), '\n')
# data['용도'].value_counts()

# 해야 할 부분
년도별로 나누기
지역별로 합치기
연료별로 합치기

## 2. 연도별 지역별로 건수 묶기

- 연도별로 묶기

In [151]:
# 2020년도
df20 = data[(data['등록연도'] == 2020)]

# 21년도 전기가 아닌것
df21 = data[(data['등록연도'] == 2021)]

In [152]:
# 2020년
df20

      등록연도 사용본거지  시군구코드   용도 차종종별       연료     건수
1     2020   종로구  11110   관용   승용      휘발유    155
2     2020   종로구  11110   관용   화물       경유    330
3     2020   종로구  11110   관용   화물     기타연료      3
4     2020   종로구  11110   관용   특수     기타연료      2
5     2020   종로구  11110  자가용   화물      휘발유     71
...    ...   ...    ...  ...  ...      ...    ...
1600  2020   강동구  11740  영업용   화물       경유   2077
1680  2020   강동구  11740  자가용   승합     기타연료     68
1681  2020   강동구  11740  자가용   화물       경유  11506
1682  2020   강동구  11740  영업용   특수       경유    228
1734  2020   강동구  11740  영업용   승용  휘발유(무연)    245

[1519 rows x 7 columns]

In [153]:
# 2021년
df21

      등록연도 사용본거지  시군구코드   용도 차종종별       연료     건수
1294  2021   종로구  11110  자가용   승용       경유  10168
1295  2021   종로구  11110  자가용   승용      CNG      8
1296  2021   종로구  11110  자가용   승합      엘피지    198
1297  2021   종로구  11110  영업용   승용  휘발유(무연)    205
1298  2021    중구  11140   관용   승용       전기    145
...    ...   ...    ...  ...  ...      ...    ...
3073  2021   송파구  11710  영업용   승용       수소      2
3074  2021   송파구  11710  영업용   승합  휘발유(무연)      1
3075  2021   강동구  11740  자가용   승합     기타연료     70
3076  2021   강동구  11740  자가용   특수     기타연료     27
3077  2021   강동구  11740  영업용   승합      엘피지    179

[1558 rows x 7 columns]

### 1) 지역별로 신규건수 묶기

In [154]:
# 20년

df_20 = pd.pivot_table(df20,
                     values = '건수',
                     index = '사용본거지',
                     columns = '연료',
                     aggfunc = 'sum')
df_20

연료,CNG,경유,기타연료,수소,엘피지,전기,하이브리드(CNG+전기),하이브리드(LPG+전기),하이브리드(경유+전기),하이브리드(휘발유+전기),휘발유,휘발유(무연),휘발유(유연)
사용본거지,,,,,,,,,,,,,
강남구,274.0,69776.0,616.0,129.0,11306.0,7495.0,NaN,86.0,156.0,13520.0,66858.0,65913.0,87.0
강동구,235.0,52165.0,292.0,132.0,14770.0,649.0,2.0,68.0,40.0,5377.0,30088.0,45991.0,57.0
강북구,675.0,27997.0,97.0,16.0,8209.0,298.0,NaN,42.0,10.0,1776.0,13437.0,23102.0,20.0
강서구,411.0,70983.0,316.0,88.0,20939.0,805.0,NaN,105.0,49.0,9749.0,39237.0,62296.0,76.0
관악구,245.0,42162.0,146.0,45.0,11063.0,412.0,NaN,100.0,16.0,3668.0,23130.0,38361.0,45.0
광진구,191.0,36890.0,146.0,30.0,7922.0,304.0,NaN,53.0,47.0,3004.0,20568.0,29694.0,34.0
구로구,374.0,55409.0,282.0,143.0,13998.0,944.0,NaN,105.0,17.0,4107.0,25434.0,44404.0,50.0
금천구,398.0,36629.0,148.0,20.0,7489.0,439.0,NaN,89.0,18.0,2251.0,14266.0,26605.0,43.0
노원구,608.0,50741.0,259.0,33.0,17182.0,495.0,31.0,102.0,24.0,4492.0,28904.0,49810.0,48.0
도봉구,354.0,34019.0,145.0,23.0,11755.0,347.0,8.0,59.0,21.0,2249.0,17103.0,29721.0,35.0
동대문구,54.0,37125.0,188.0,37.0,8753.0,312.0,NaN,50.0,29.0,2694.0,19350.0,29406.0,32.0
동작구,65.0,35112.0,120.0,67.0,7480.0,390.0,NaN,71.0,31.0,3959.0,23568.0,34689.0,36.0
마포구,325.0,41768.0,261.0,96.0,8231.0,567.0,NaN,59.0,40.0,4411.0,26959.0,36640.0,32.0
서대문구,284.0,30408.0,162.0,63.0,7851.0,358.0,2.0,56.0,21.0,3086.0,18854.0,28315.0,36.0
서초구,538.0,58746.0,404.0,158.0,7503.0,2058.0,NaN,65.0,75.0,8228.0,50897.0,52313.0,68.0
성동구,464.0,37886.0,190.0,34.0,8190.0,1041.0,NaN,77.0,52.0,3441.0,21979.0,32765.0,37.0
성북구,743.0,42296.0,216.0,35.0,9555.0,530.0,3.0,57.0,32.0,3732.0,24686.0,38342.0,42.0
송파구,834.0,87498.0,488.0,116.0,16788.0,1075.0,4.0,129.0,94.0,9391.0,56439.0,72875.0,102.0
양천구,618.0,51508.0,297.0,59.0,13921.0,557.0,NaN,98.0,30.0,4912.0,32709.0,46698.0,42.0
영등포구,115.0,55172.0,433.0,110.0,9799.0,1942.0,NaN,105.0,40.0,5250.0,29655.0,43493.0,57.0
용산구,28.0,26069.0,261.0,44.0,3653.0,479.0,NaN,26.0,25.0,3049.0,23281.0,22059.0,21.0
은평구,746.0,45175.0,196.0,81.0,12851.0,492.0,1.0,96.0,18.0,3889.0,26376.0,42231.0,46.0
종로구,124.0,18504.0,181.0,52.0,2421.0,278.0,NaN,29.0,16.0,1844.0,11285.0,15526.0,7.0
중구,34.0,20600.0,286.0,32.0,3061.0,714.0,NaN,24.0,29.0,1819.0,11217.0,13298.0,12.0
중랑구,377.0,43649.0,175.0,28.0,13754.0,412.0,NaN,61.0,20.0,2569.0,19302.0,33641.0,32.0

In [155]:
# null 값 확인

df20[df20['연료']=="하이브리드(CNG+전기)"]

# null 값 0으로 변경
df_20.fillna(0, inplace = True)

# int로 변경
df_20 = df_20.astype(int)
df_20.head()

연료,CNG,경유,기타연료,수소,엘피지,전기,하이브리드(CNG+전기),하이브리드(LPG+전기),하이브리드(경유+전기),하이브리드(휘발유+전기),휘발유,휘발유(무연),휘발유(유연)
사용본거지,,,,,,,,,,,,,
강남구,274,69776,616,129,11306,7495,0,86,156,13520,66858,65913,87
강동구,235,52165,292,132,14770,649,2,68,40,5377,30088,45991,57
강북구,675,27997,97,16,8209,298,0,42,10,1776,13437,23102,20
강서구,411,70983,316,88,20939,805,0,105,49,9749,39237,62296,76
관악구,245,42162,146,45,11063,412,0,100,16,3668,23130,38361,45

In [156]:
# 21년
df_21 = pd.pivot_table(df21,
                     values = '건수',
                     index = '사용본거지',
                     columns = '연료',
                     aggfunc = 'sum')
df_21

연료,CNG,경유,기타연료,수소,엘피지,전기,하이브리드(CNG+전기),하이브리드(LPG+전기),하이브리드(경유+전기),하이브리드(휘발유+전기),휘발유,휘발유(무연),휘발유(유연)
사용본거지,,,,,,,,,,,,,
강남구,268.0,68130.0,579.0,192.0,10801.0,11432.0,NaN,69.0,308.0,15154.0,66159.0,66463.0,88.0
강동구,216.0,51420.0,326.0,206.0,14014.0,1273.0,2.0,73.0,95.0,6716.0,30081.0,47700.0,56.0
강북구,658.0,27260.0,119.0,25.0,7772.0,496.0,NaN,41.0,29.0,2204.0,13148.0,23564.0,21.0
강서구,388.0,69268.0,367.0,131.0,19782.0,1679.0,NaN,97.0,113.0,10560.0,38643.0,63962.0,68.0
관악구,225.0,40921.0,158.0,65.0,10436.0,730.0,NaN,85.0,43.0,4447.0,22294.0,38624.0,54.0
광진구,186.0,35961.0,159.0,47.0,7354.0,590.0,NaN,52.0,98.0,3853.0,20158.0,29882.0,31.0
구로구,389.0,53733.0,312.0,161.0,12805.0,3733.0,NaN,94.0,49.0,5030.0,24599.0,44927.0,42.0
금천구,386.0,36564.0,170.0,35.0,7492.0,530.0,NaN,80.0,50.0,2910.0,14113.0,27799.0,40.0
노원구,599.0,49525.0,298.0,62.0,16239.0,889.0,31.0,96.0,46.0,5650.0,28329.0,50474.0,47.0
도봉구,353.0,33366.0,164.0,25.0,11099.0,637.0,8.0,58.0,38.0,2907.0,16744.0,30196.0,36.0
동대문구,47.0,36304.0,210.0,52.0,8320.0,656.0,NaN,45.0,66.0,3517.0,19078.0,30141.0,30.0
동작구,57.0,34365.0,144.0,98.0,7085.0,710.0,NaN,61.0,65.0,4978.0,23395.0,35235.0,36.0
마포구,319.0,41400.0,281.0,146.0,7761.0,1062.0,NaN,59.0,99.0,5565.0,26914.0,37721.0,37.0
서대문구,261.0,29514.0,198.0,83.0,7349.0,663.0,2.0,41.0,55.0,3833.0,18500.0,28671.0,29.0
서초구,529.0,55125.0,429.0,246.0,6866.0,3616.0,NaN,50.0,157.0,9987.0,48275.0,51801.0,52.0
성동구,459.0,36739.0,333.0,51.0,7733.0,1494.0,NaN,80.0,126.0,4382.0,21644.0,34484.0,39.0
성북구,735.0,41705.0,255.0,67.0,9106.0,900.0,3.0,53.0,73.0,4843.0,24521.0,38773.0,39.0
송파구,826.0,85730.0,602.0,184.0,16200.0,1932.0,4.0,106.0,210.0,11789.0,55219.0,73962.0,94.0
양천구,611.0,50027.0,314.0,85.0,13218.0,989.0,NaN,89.0,79.0,6160.0,32130.0,47593.0,43.0
영등포구,110.0,53559.0,456.0,162.0,9342.0,2409.0,NaN,100.0,80.0,6383.0,29216.0,44220.0,58.0
용산구,29.0,24963.0,263.0,61.0,3453.0,957.0,NaN,31.0,76.0,3999.0,23287.0,22604.0,17.0
은평구,705.0,44471.0,216.0,106.0,12304.0,881.0,1.0,82.0,47.0,4896.0,26199.0,43221.0,46.0
종로구,121.0,18058.0,207.0,70.0,2293.0,606.0,NaN,29.0,33.0,2440.0,11027.0,15453.0,11.0
중구,36.0,23858.0,290.0,39.0,2962.0,950.0,NaN,23.0,88.0,2507.0,16834.0,13560.0,11.0
중랑구,374.0,42775.0,185.0,46.0,13255.0,750.0,NaN,53.0,48.0,3310.0,19102.0,34440.0,37.0

In [157]:
# null 값 0으로 변경
df_21.fillna(0, inplace = True)

# int로 변경
df_21 = df_21.astype(int)
df_21.head()

연료,CNG,경유,기타연료,수소,엘피지,전기,하이브리드(CNG+전기),하이브리드(LPG+전기),하이브리드(경유+전기),하이브리드(휘발유+전기),휘발유,휘발유(무연),휘발유(유연)
사용본거지,,,,,,,,,,,,,
강남구,268,68130,579,192,10801,11432,0,69,308,15154,66159,66463,88
강동구,216,51420,326,206,14014,1273,2,73,95,6716,30081,47700,56
강북구,658,27260,119,25,7772,496,0,41,29,2204,13148,23564,21
강서구,388,69268,367,131,19782,1679,0,97,113,10560,38643,63962,68
관악구,225,40921,158,65,10436,730,0,85,43,4447,22294,38624,54

### 2) 지역별로 차종종별 count

In [158]:
# 20년

df_20_type = pd.pivot_table(df20,
                     values = '건수',
                     index = '사용본거지',
                     columns = ['차종종별','연료'],
                     aggfunc = 'sum')
df_20_type.head()

차종종별     승용                                                                    \
연료      CNG       경유  기타연료     수소      엘피지      전기 하이브리드(LPG+전기) 하이브리드(경유+전기)
사용본거지
강남구    33.0  51243.0  12.0  129.0   9510.0  7423.0          86.0        156.0
강동구    38.0  34658.0   6.0  132.0  12892.0   552.0          68.0         40.0
강북구     9.0  17682.0   NaN   16.0   6857.0   222.0          42.0         10.0
강서구    27.0  45993.0   3.0   88.0  18497.0   695.0         105.0         49.0
관악구    13.0  27827.0   NaN   45.0   9407.0   327.0         100.0         16.0

차종종별                          ...   특수                 화물                  \
연료    하이브리드(휘발유+전기)      휘발유  ...   전기  휘발유 휘발유(무연)   CNG       경유   기타연료
사용본거지                         ...
강남구         13520.0  66654.0  ...  NaN  4.0     2.0  41.0  13912.0  479.0
강동구          5377.0  29989.0  ...  NaN  NaN     NaN  16.0  13711.0  205.0
강북구          1776.0  13380.0  ...  NaN  1.0     NaN   9.0   7862.0   72.0
강서구          9749.0  39127.0  ...  1.0  NaN     1.0   9.0  18929.0  228.0
관악구          3668.0  23067.0  ...  NaN  NaN     NaN  11.0  10690.0  114.0

차종종별
연료        엘피지    전기    휘발유 휘발유(무연)
사용본거지
강남구     992.0  72.0  152.0   104.0
강동구    1173.0  77.0   77.0    28.0
강북구     854.0  56.0   43.0     9.0
강서구    1503.0  89.0   86.0    38.0
관악구    1066.0  44.0   50.0    23.0

[5 rows x 36 columns]

In [159]:
# null값 제거
df_20_type.fillna(0, inplace = True)

# int로 변경
df_20_type = df_20_type.astype(int)
df_20_type.head()

차종종별   승용                                                           \
연료    CNG     경유 기타연료   수소    엘피지    전기 하이브리드(LPG+전기) 하이브리드(경유+전기)
사용본거지
강남구    33  51243   12  129   9510  7423            86          156
강동구    38  34658    6  132  12892   552            68           40
강북구     9  17682    0   16   6857   222            42           10
강서구    27  45993    3   88  18497   695           105           49
관악구    13  27827    0   45   9407   327           100           16

차종종별                        ... 특수              화물                             \
연료    하이브리드(휘발유+전기)    휘발유  ... 전기 휘발유 휘발유(무연) CNG     경유 기타연료   엘피지  전기  휘발유
사용본거지                       ...
강남구           13520  66654  ...  0   4       2  41  13912  479   992  72  152
강동구            5377  29989  ...  0   0       0  16  13711  205  1173  77   77
강북구            1776  13380  ...  0   1       0   9   7862   72   854  56   43
강서구            9749  39127  ...  1   0       1   9  18929  228  1503  89   86
관악구            3668  23067  ...  0   0       0  11  10690  114  1066  44   50

차종종별
연료    휘발유(무연)
사용본거지
강남구       104
강동구        28
강북구         9
강서구        38
관악구        23

[5 rows x 36 columns]

In [160]:
# 21년

df_21_type = pd.pivot_table(df21,
                     values = '건수',
                     index = '사용본거지',
                     columns = ['차종종별', '연료'],
                     aggfunc = 'sum')
df_21_type.head()

차종종별     승용                                                        \
연료      CNG       경유  기타연료     수소      엘피지       전기 하이브리드(LPG+전기)
사용본거지
강남구    35.0  50159.0  11.0  192.0   9175.0  11231.0          69.0
강동구    27.0  34301.0   4.0  206.0  12081.0   1009.0          73.0
강북구     7.0  17273.0   NaN   25.0   6522.0    341.0          41.0
강서구    20.0  44796.0   3.0  131.0  17597.0   1328.0          97.0
관악구     7.0  27142.0   NaN   65.0   8947.0    556.0          85.0

차종종별                                       ...   특수            화물           \
연료    하이브리드(경유+전기) 하이브리드(휘발유+전기)      휘발유  ...  휘발유 휘발유(무연)   CNG       경유
사용본거지                                      ...
강남구          308.0       15154.0  65927.0  ...  5.0     2.0  34.0  13686.0
강동구           95.0        6716.0  29970.0  ...  NaN     NaN  14.0  13431.0
강북구           29.0        2204.0  13084.0  ...  1.0     NaN   7.0   7629.0
강서구          113.0       10560.0  38497.0  ...  NaN     1.0   8.0  18863.0
관악구           43.0        4446.0  22217.0  ...  NaN     NaN   4.0  10327.0

차종종별
연료      기타연료     엘피지     전기 하이브리드(휘발유+전기)    휘발유 휘발유(무연)
사용본거지
강남구    439.0   914.0  196.0           NaN  172.0   105.0
강동구    225.0  1120.0  237.0           NaN   92.0    29.0
강북구     92.0   801.0  113.0           NaN   51.0    11.0
강서구    258.0  1385.0  314.0           NaN  121.0    40.0
관악구    124.0   958.0  127.0           1.0   64.0    21.0

[5 rows x 37 columns]

In [161]:
# null값 제거
df_21_type.fillna(0, inplace = True)

# int로 변경
df_21_type = df_21_type.astype(int)
df_21_type.head()

차종종별   승용                                                            \
연료    CNG     경유 기타연료   수소    엘피지     전기 하이브리드(LPG+전기) 하이브리드(경유+전기)
사용본거지
강남구    35  50159   11  192   9175  11231            69          308
강동구    27  34301    4  206  12081   1009            73           95
강북구     7  17273    0   25   6522    341            41           29
강서구    20  44796    3  131  17597   1328            97          113
관악구     7  27142    0   65   8947    556            85           43

차종종별                        ...  특수          화물                         \
연료    하이브리드(휘발유+전기)    휘발유  ... 휘발유 휘발유(무연) CNG     경유 기타연료   엘피지   전기
사용본거지                       ...
강남구           15154  65927  ...   5       2  34  13686  439   914  196
강동구            6716  29970  ...   0       0  14  13431  225  1120  237
강북구            2204  13084  ...   1       0   7   7629   92   801  113
강서구           10560  38497  ...   0       1   8  18863  258  1385  314
관악구            4446  22217  ...   0       0   4  10327  124   958  127

차종종별
연료    하이브리드(휘발유+전기)  휘발유 휘발유(무연)
사용본거지
강남구               0  172     105
강동구               0   92      29
강북구               0   51      11
강서구               0  121      40
관악구               1   64      21

[5 rows x 37 columns]

## 3. 파일 저장

In [168]:
# json 파일로 저장

# 전체 20년 데이터
df_20.to_json("total_car20.json", orient = 'columns')

# 전체 21년 데이터
df_21.to_json("total_car21.json", orient = 'columns')

# 차종별 20년 데이터
df_20_type.to_json("type_car20.json", orient = 'columns')

# 차종별 21년 데이터
df_21_type.to_json("type_car21.json", orient = 'columns')

In [169]:
# 확인

df_read_20 = pd.read_json('total_car20.json')
df_read_20.head()

,CNG,경유,기타연료,수소,엘피지,전기,하이브리드(CNG+전기),하이브리드(LPG+전기),하이브리드(경유+전기),하이브리드(휘발유+전기),휘발유,휘발유(무연),휘발유(유연)
강남구,274,69776,616,129,11306,7495,0,86,156,13520,66858,65913,87
강동구,235,52165,292,132,14770,649,2,68,40,5377,30088,45991,57
강북구,675,27997,97,16,8209,298,0,42,10,1776,13437,23102,20
강서구,411,70983,316,88,20939,805,0,105,49,9749,39237,62296,76
관악구,245,42162,146,45,11063,412,0,100,16,3668,23130,38361,45

In [170]:
df_read_21 = pd.read_json('total_car21.json')
df_read_21.head()

,CNG,경유,기타연료,수소,엘피지,전기,하이브리드(CNG+전기),하이브리드(LPG+전기),하이브리드(경유+전기),하이브리드(휘발유+전기),휘발유,휘발유(무연),휘발유(유연)
강남구,268,68130,579,192,10801,11432,0,69,308,15154,66159,66463,88
강동구,216,51420,326,206,14014,1273,2,73,95,6716,30081,47700,56
강북구,658,27260,119,25,7772,496,0,41,29,2204,13148,23564,21
강서구,388,69268,367,131,19782,1679,0,97,113,10560,38643,63962,68
관악구,225,40921,158,65,10436,730,0,85,43,4447,22294,38624,54

In [171]:
df_read_t20 = pd.read_json('type_car20.json')
df_read_t20.head()

,"('승용', 'CNG')","('승용', '경유')","('승용', '기타연료')","('승용', '수소')","('승용', '엘피지')","('승용', '전기')","('승용', '하이브리드(LPG+전기)')","('승용', '하이브리드(경유+전기)')","('승용', '하이브리드(휘발유+전기)')","('승용', '휘발유')",...,"('특수', '전기')","('특수', '휘발유')","('특수', '휘발유(무연)')","('화물', 'CNG')","('화물', '경유')","('화물', '기타연료')","('화물', '엘피지')","('화물', '전기')","('화물', '휘발유')","('화물', '휘발유(무연)')"
강남구,33,51243,12,129,9510,7423,86,156,13520,66654,...,0,4,2,41,13912,479,992,72,152,104
강동구,38,34658,6,132,12892,552,68,40,5377,29989,...,0,0,0,16,13711,205,1173,77,77,28
강북구,9,17682,0,16,6857,222,42,10,1776,13380,...,0,1,0,9,7862,72,854,56,43,9
강서구,27,45993,3,88,18497,695,105,49,9749,39127,...,1,0,1,9,18929,228,1503,89,86,38
관악구,13,27827,0,45,9407,327,100,16,3668,23067,...,0,0,0,11,10690,114,1066,44,50,23

In [172]:
df_read_t21 = pd.read_json('type_car21.json')
df_read_t21.head()

,"('승용', 'CNG')","('승용', '경유')","('승용', '기타연료')","('승용', '수소')","('승용', '엘피지')","('승용', '전기')","('승용', '하이브리드(LPG+전기)')","('승용', '하이브리드(경유+전기)')","('승용', '하이브리드(휘발유+전기)')","('승용', '휘발유')",...,"('특수', '휘발유')","('특수', '휘발유(무연)')","('화물', 'CNG')","('화물', '경유')","('화물', '기타연료')","('화물', '엘피지')","('화물', '전기')","('화물', '하이브리드(휘발유+전기)')","('화물', '휘발유')","('화물', '휘발유(무연)')"
강남구,35,50159,11,192,9175,11231,69,308,15154,65927,...,5,2,34,13686,439,914,196,0,172,105
강동구,27,34301,4,206,12081,1009,73,95,6716,29970,...,0,0,14,13431,225,1120,237,0,92,29
강북구,7,17273,0,25,6522,341,41,29,2204,13084,...,1,0,7,7629,92,801,113,0,51,11
강서구,20,44796,3,131,17597,1328,97,113,10560,38497,...,0,1,8,18863,258,1385,314,0,121,40
관악구,7,27142,0,65,8947,556,85,43,4446,22217,...,0,0,4,10327,124,958,127,1,64,21

# <19년 전기차 신규등록 (소유 파악) - 종속변수>

In [173]:
data2 = pd.read_csv("2019년 연료별 자동차 등록현황.csv", encoding = 'cp949')
# 19년 자치구별 연료별 자동차 등록현황(서울열린데이터광장)
data2

           년월 시군구별      연료별   용도별     승용     승합     화물     특수       계
0     2019-01  종로구      CNG  비사업용       6      2     16    NaN      24
1     2019-01  종로구      CNG   사업용     NaN     92    NaN    NaN      92
2     2019-01  종로구       경유  비사업용  11,053  3,266  4,114  120.0  18,553
3     2019-01  종로구       경유   사업용      56    224    602   53.0     935
4     2019-01  종로구     기타연료  비사업용       2     25     47   10.0      84
...       ...  ...      ...   ...     ...    ...    ...    ...     ...
6142  2019-12  강동구      휘발유  비사업용  28,180     19     55    NaN  28,254
6143  2019-12  강동구      휘발유   사업용      70      3    NaN    NaN      73
6144  2019-12  강동구  휘발유(무연)  비사업용  41,276     19     28    NaN  41,323
6145  2019-12  강동구  휘발유(무연)   사업용     232    NaN    NaN    NaN     232
6146  2019-12  강동구  휘발유(유연)  비사업용      52    NaN    NaN    NaN      52

[6147 rows x 9 columns]

## 1. 컬럼 값 확인 및 정리

## 1-1) 컬럼 정리

In [174]:
# 컬럼명 변경
for i in range(len(data2['년월'])):
    data2.iloc[i, 0] = int(data2.iloc[i, 0][:4])
    
data2['년월']

0       2019
1       2019
2       2019
3       2019
4       2019
        ...
6142    2019
6143    2019
6144    2019
6145    2019
6146    2019
Name: 년월, Length: 6147, dtype: object

In [175]:
# 컬럼명 변경
data2.columns = ['등록연도', '사용본거지', '연료', '용도', '승용', '승합', '화물', '특수', '합계']
data2.head()

   등록연도 사용본거지    연료    용도      승용     승합     화물     특수      합계
0  2019   종로구   CNG  비사업용       6      2     16    NaN      24
1  2019   종로구   CNG   사업용     NaN     92    NaN    NaN      92
2  2019   종로구    경유  비사업용  11,053  3,266  4,114  120.0  18,553
3  2019   종로구    경유   사업용      56    224    602   53.0     935
4  2019   종로구  기타연료  비사업용       2     25     47   10.0      84

In [176]:
data2.fillna(0, inplace = True)
data2.head()

   등록연도 사용본거지    연료    용도      승용     승합     화물     특수      합계
0  2019   종로구   CNG  비사업용       6      2     16    0.0      24
1  2019   종로구   CNG   사업용       0     92      0    0.0      92
2  2019   종로구    경유  비사업용  11,053  3,266  4,114  120.0  18,553
3  2019   종로구    경유   사업용      56    224    602   53.0     935
4  2019   종로구  기타연료  비사업용       2     25     47   10.0      84

In [177]:
# 값 확인
print(data2.isnull().sum(), '\n')
print(data2.dtypes, '\n')
print("****사용본거지****", '\n', data2['사용본거지'].value_counts(), '\n')
print("****연료", '\n', data2["연료"].value_counts(), '\n')
print("****용도****", '\n', data2['용도'].value_counts())

등록연도     0
사용본거지    0
연료       0
용도       0
승용       0
승합       0
화물       0
특수       0
합계       0
dtype: int64

등록연도       int64
사용본거지     object
연료        object
용도        object
승용        object
승합        object
화물        object
특수       float64
합계        object
dtype: object

****사용본거지****
 금천구     268
송파구     264
강남구     260
양천구     257
영등포구    256
서대문구    252
노원구     252
서초구     252
강동구     252
은평구     250
성동구     246
도봉구     244
강서구     244
구로구     243
광진구     243
강북구     240
중구      240
관악구     240
성북구     239
중랑구     239
동작구     239
용산구     235
마포구     234
종로구     230
동대문구    228
Name: 사용본거지, dtype: int64

****연료
 CNG              600
경유               600
기타연료             600
엘피지              600
휘발유(무연)          600
휘발유              593
하이브리드(휘발유+전기)    591
전기               586
하이브리드(LPG+전기)    359
휘발유(유연)          355
수소               345
하이브리드(경유+전기)     234
하이브리드(CNG+전기)     84
Name: 연료, dtype: int64

****용도****
 비사업용    3528
사업용     2619
Name: 용도, dtype: int64

In [178]:
len(data2)

6147

In [179]:
# 천단위 때문에 문자열 변경이 어려워 정규식으로 , 제거
data2['승용'] = data2['승용'].str.replace(',','')
data2['승합'] = data2['승합'].str.replace(',','')
data2['화물'] = data2['화물'].str.replace(',','')
data2['합계'] = data2['합계'].str.replace(',','')

# null 값 제거
data2.fillna(0, inplace = True)

# 문자로 변경
data2 = data2.astype({'승용':int,
                     '승합':int,
                     '화물':int,
                     '특수':int,
                     '합계':int})
data2.dtypes

등록연도      int64
사용본거지    object
연료       object
용도       object
승용        int32
승합        int32
화물        int32
특수        int32
합계        int32
dtype: object

## 1-2) 20, 21년도와 같은 형태로 만들기

In [180]:
# 새로운 데이터프레임 형성
data3 = data2[['사용본거지', '연료', '용도']]
data3

     사용본거지       연료    용도
0      종로구      CNG  비사업용
1      종로구      CNG   사업용
2      종로구       경유  비사업용
3      종로구       경유   사업용
4      종로구     기타연료  비사업용
...    ...      ...   ...
6142   강동구      휘발유  비사업용
6143   강동구      휘발유   사업용
6144   강동구  휘발유(무연)  비사업용
6145   강동구  휘발유(무연)   사업용
6146   강동구  휘발유(유연)  비사업용

[6147 rows x 3 columns]

In [181]:
# 중복제거
dt = data3.drop_duplicates(['사용본거지', '연료', '용도'])
dt = dt.reset_index()
dt = dt.drop('index', axis= 1)
dt

    사용본거지             연료    용도
0     종로구            CNG  비사업용
1     종로구            CNG   사업용
2     종로구             경유  비사업용
3     종로구             경유   사업용
4     종로구           기타연료  비사업용
..    ...            ...   ...
520   금천구             수소   사업용
521   강북구  하이브리드(LPG+전기)   사업용
522   구로구  하이브리드(LPG+전기)   사업용
523   종로구             전기   사업용
524  영등포구             수소   사업용

[525 rows x 3 columns]

In [182]:
# 차종종별로 건수 추가하기

li1 = data2["사용본거지"].unique().tolist()

li2 = data2["연료"].unique().tolist()

# 용도 리스트
li3 = data2["용도"].unique().tolist()

# 승용
dt1 = dt.copy()
dt1['차종종별'] = '승용'
dt1['건수'] = 0

# 승합
dt2 = dt.copy()
dt2['차종종별'] = '승합'
dt2['건수'] = 0

# 화물
dt3 = dt.copy()
dt3['차종종별'] = '화물'
dt3['건수'] = 0

# 특수
dt4 = dt.copy()
dt4['차종종별'] = '특수'
dt4['건수'] = 0

# 해당 값 추가
for a in li1:
    for b in li2:
        for c in li3:
            dt1['건수'][(dt1['사용본거지']==a)&(dt1['연료']==b)&(dt1['용도']==c)] = data2['승용'][(data2['사용본거지']==a)&(data2['연료']==b)&(data2['용도']==c)].sum()
            dt2['건수'][(dt2['사용본거지']==a)&(dt2['연료']==b)&(dt2['용도']==c)] = data2['승용'][(data2['사용본거지']==a)&(data2['연료']==b)&(data2['용도']==c)].sum()
            dt3['건수'][(dt3['사용본거지']==a)&(dt3['연료']==b)&(dt3['용도']==c)] = data2['승용'][(data2['사용본거지']==a)&(data2['연료']==b)&(data2['용도']==c)].sum()
            dt4['건수'][(dt4['사용본거지']==a)&(dt4['연료']==b)&(dt4['용도']==c)] = data2['승용'][(data2['사용본거지']==a)&(data2['연료']==b)&(data2['용도']==c)].sum()
                    
# 데이터프레임 행방향 합치기
result = pd.concat([dt1,dt2,dt3,dt4], ignore_index=True)
result.head()

  사용본거지    연료    용도 차종종별      건수
0   종로구   CNG  비사업용   승용      79
1   종로구   CNG   사업용   승용       0
2   종로구    경유  비사업용   승용  129700
3   종로구    경유   사업용   승용     695
4   종로구  기타연료  비사업용   승용      24

In [183]:
result

     사용본거지             연료    용도 차종종별      건수
0      종로구            CNG  비사업용   승용      79
1      종로구            CNG   사업용   승용       0
2      종로구             경유  비사업용   승용  129700
3      종로구             경유   사업용   승용     695
4      종로구           기타연료  비사업용   승용      24
...    ...            ...   ...  ...     ...
2095   금천구             수소   사업용   특수       4
2096   강북구  하이브리드(LPG+전기)   사업용   특수       3
2097   구로구  하이브리드(LPG+전기)   사업용   특수       8
2098   종로구             전기   사업용   특수       6
2099  영등포구             수소   사업용   특수       6

[2100 rows x 5 columns]

In [184]:
# 값 확인
print(result.isnull().sum(), '\n')
print(result.dtypes, '\n')
print("****사용본거지****", '\n', result['사용본거지'].value_counts(), '\n')
print("****연료", '\n', result["연료"].value_counts(), '\n')
print("****용도****", '\n', result['용도'].value_counts())

사용본거지    0
연료       0
용도       0
차종종별     0
건수       0
dtype: int64

사용본거지    object
연료       object
용도       object
차종종별     object
건수        int64
dtype: object

****사용본거지****
 영등포구    92
금천구     92
은평구     88
송파구     88
강남구     88
양천구     88
서대문구    84
서초구     84
동작구     84
구로구     84
강서구     84
강동구     84
노원구     84
도봉구     84
강북구     84
성북구     84
광진구     84
성동구     84
중구      80
마포구     80
중랑구     80
관악구     80
용산구     80
종로구     80
동대문구    76
Name: 사용본거지, dtype: int64

****연료
 CNG              200
경유               200
기타연료             200
엘피지              200
전기               200
하이브리드(휘발유+전기)    200
휘발유              200
휘발유(무연)          200
하이브리드(LPG+전기)    132
수소               128
휘발유(유연)          120
하이브리드(경유+전기)      92
하이브리드(CNG+전기)     28
Name: 연료, dtype: int64

****용도****
 비사업용    1192
사업용      908
Name: 용도, dtype: int64

## 2. 지역별 묶기

### 1) 지역별로 건수 합

In [185]:
df_19 = pd.pivot_table(result,
                     values = '건수',
                     index = '사용본거지',
                     columns = '연료',
                     aggfunc = 'sum')
df_19

연료,CNG,경유,기타연료,수소,엘피지,전기,하이브리드(CNG+전기),하이브리드(LPG+전기),하이브리드(경유+전기),하이브리드(휘발유+전기),휘발유,휘발유(무연),휘발유(유연)
사용본거지,,,,,,,,,,,,,
강남구,2268.0,2522728.0,664.0,1700.0,497240.0,231756.0,NaN,5048.0,280.0,515744.0,3241620.0,3141596.0,3940.0
강동구,1784.0,1519864.0,268.0,304.0,620700.0,11552.0,0.0,3652.0,48.0,155120.0,1327376.0,1915836.0,2444.0
강북구,656.0,877164.0,48.0,84.0,366020.0,5632.0,NaN,2452.0,84.0,59456.0,656016.0,1074316.0,1132.0
강서구,2032.0,2266156.0,188.0,380.0,947224.0,16116.0,NaN,5504.0,108.0,355428.0,1915728.0,2857536.0,3808.0
관악구,1116.0,1386844.0,0.0,160.0,478448.0,8820.0,NaN,5352.0,72.0,129980.0,1158472.0,1785584.0,2452.0
광진구,676.0,1157204.0,0.0,224.0,337816.0,7460.0,NaN,2844.0,40.0,107224.0,1006192.0,1387948.0,1940.0
구로구,1476.0,1697432.0,0.0,384.0,636352.0,10064.0,NaN,5032.0,NaN,138720.0,1241300.0,2032508.0,2228.0
금천구,908.0,1033188.0,48.0,196.0,325376.0,8516.0,NaN,2972.0,8.0,75168.0,695888.0,1192708.0,1924.0
노원구,1620.0,1744992.0,96.0,132.0,770632.0,10016.0,0.0,5124.0,140.0,152660.0,1431016.0,2288272.0,2456.0
도봉구,864.0,1080516.0,48.0,148.0,526424.0,7420.0,0.0,3092.0,36.0,81320.0,852432.0,1378564.0,1704.0
동대문구,580.0,1142296.0,144.0,164.0,363624.0,6488.0,NaN,3052.0,NaN,90604.0,938632.0,1346100.0,1744.0
동작구,752.0,1223652.0,96.0,248.0,326020.0,9864.0,NaN,3608.0,72.0,141412.0,1170644.0,1611008.0,1876.0
마포구,1180.0,1357056.0,96.0,588.0,360856.0,12932.0,NaN,3156.0,48.0,148756.0,1286224.0,1683064.0,1716.0
서대문구,624.0,977368.0,96.0,476.0,346352.0,7916.0,0.0,2724.0,64.0,100324.0,896088.0,1273972.0,1668.0
서초구,1484.0,1984744.0,308.0,1952.0,318260.0,38852.0,NaN,3444.0,188.0,319788.0,2484196.0,2499772.0,3408.0
성동구,832.0,1274440.0,104.0,296.0,349156.0,24952.0,NaN,3164.0,60.0,124740.0,1077556.0,1455796.0,1968.0
성북구,872.0,1419720.0,112.0,256.0,417920.0,10168.0,0.0,2924.0,36.0,126744.0,1183940.0,1719876.0,1812.0
송파구,2880.0,2651996.0,96.0,796.0,731116.0,22000.0,0.0,7584.0,332.0,324284.0,2749056.0,3383100.0,4956.0
양천구,984.0,1663760.0,96.0,356.0,605988.0,11820.0,NaN,4508.0,96.0,166044.0,1587304.0,2144188.0,1792.0
영등포구,556.0,1619984.0,192.0,548.0,411780.0,37100.0,NaN,4872.0,96.0,176912.0,1400296.0,1946424.0,3036.0
용산구,116.0,883600.0,8236.0,228.0,155512.0,11952.0,NaN,1524.0,48.0,97764.0,1051332.0,1021028.0,1108.0
은평구,832.0,1463060.0,96.0,592.0,563396.0,9088.0,0.0,5196.0,60.0,129300.0,1259600.0,1915304.0,1828.0
종로구,316.0,521580.0,96.0,660.0,91048.0,7392.0,NaN,1920.0,76.0,66468.0,547368.0,726976.0,476.0
중구,360.0,598596.0,192.0,264.0,109304.0,12196.0,NaN,1284.0,460.0,67900.0,545496.0,634944.0,788.0
중랑구,984.0,1289984.0,96.0,140.0,596572.0,7836.0,NaN,2940.0,48.0,84652.0,941200.0,1527328.0,1320.0

In [186]:
# null 값 확인

result[result['연료']=="하이브리드(CNG+전기)"]

# null 값 0으로 변경
df_19.fillna(0, inplace = True)

# int로 변경
df_19 = df_19.astype(int)
df_19.head()

연료,CNG,경유,기타연료,수소,엘피지,전기,하이브리드(CNG+전기),하이브리드(LPG+전기),하이브리드(경유+전기),하이브리드(휘발유+전기),휘발유,휘발유(무연),휘발유(유연)
사용본거지,,,,,,,,,,,,,
강남구,2268,2522728,664,1700,497240,231756,0,5048,280,515744,3241620,3141596,3940
강동구,1784,1519864,268,304,620700,11552,0,3652,48,155120,1327376,1915836,2444
강북구,656,877164,48,84,366020,5632,0,2452,84,59456,656016,1074316,1132
강서구,2032,2266156,188,380,947224,16116,0,5504,108,355428,1915728,2857536,3808
관악구,1116,1386844,0,160,478448,8820,0,5352,72,129980,1158472,1785584,2452

### 2) 지역별로 차종종별 count

In [187]:
df_19_type = pd.pivot_table(result,
                     values = '건수',
                     index = '사용본거지',
                     columns = ['차종종별','연료'],
                     aggfunc = 'sum')
df_19_type.head()

차종종별      승용                                                           \
연료       CNG        경유   기타연료     수소       엘피지       전기 하이브리드(CNG+전기)
사용본거지
강남구    567.0  630682.0  166.0  425.0  124310.0  57939.0           NaN
강동구    446.0  379966.0   67.0   76.0  155175.0   2888.0           0.0
강북구    164.0  219291.0   12.0   21.0   91505.0   1408.0           NaN
강서구    508.0  566539.0   47.0   95.0  236806.0   4029.0           NaN
관악구    279.0  346711.0    0.0   40.0  119612.0   2205.0           NaN

차종종별                                            ...     화물                     \
연료    하이브리드(LPG+전기) 하이브리드(경유+전기) 하이브리드(휘발유+전기)  ...     수소       엘피지       전기
사용본거지                                           ...
강남구          1262.0         70.0      128936.0  ...  425.0  124310.0  57939.0
강동구           913.0         12.0       38780.0  ...   76.0  155175.0   2888.0
강북구           613.0         21.0       14864.0  ...   21.0   91505.0   1408.0
강서구          1376.0         27.0       88857.0  ...   95.0  236806.0   4029.0
관악구          1338.0         18.0       32495.0  ...   40.0  119612.0   2205.0

차종종별                                                                    \
연료    하이브리드(CNG+전기) 하이브리드(LPG+전기) 하이브리드(경유+전기) 하이브리드(휘발유+전기)       휘발유
사용본거지
강남구             NaN        1262.0         70.0      128936.0  810405.0
강동구             0.0         913.0         12.0       38780.0  331844.0
강북구             NaN         613.0         21.0       14864.0  164004.0
강서구             NaN        1376.0         27.0       88857.0  478932.0
관악구             NaN        1338.0         18.0       32495.0  289618.0

차종종별
연료      휘발유(무연) 휘발유(유연)
사용본거지
강남구    785399.0   985.0
강동구    478959.0   611.0
강북구    268579.0   283.0
강서구    714384.0   952.0
관악구    446396.0   613.0

[5 rows x 52 columns]

In [188]:
# null 값 0으로 변경
df_19_type.fillna(0, inplace = True)

# int로 변경
df_19_type = df_19_type.astype(int)
df_19_type.head()

차종종별    승용                                                               \
연료     CNG      경유 기타연료   수소     엘피지     전기 하이브리드(CNG+전기) 하이브리드(LPG+전기)
사용본거지
강남구    567  630682  166  425  124310  57939             0          1262
강동구    446  379966   67   76  155175   2888             0           913
강북구    164  219291   12   21   91505   1408             0           613
강서구    508  566539   47   95  236806   4029             0          1376
관악구    279  346711    0   40  119612   2205             0          1338

차종종별                              ...   화물                               \
연료    하이브리드(경유+전기) 하이브리드(휘발유+전기)  ...   수소     엘피지     전기 하이브리드(CNG+전기)
사용본거지                             ...
강남구             70        128936  ...  425  124310  57939             0
강동구             12         38780  ...   76  155175   2888             0
강북구             21         14864  ...   21   91505   1408             0
강서구             27         88857  ...   95  236806   4029             0
관악구             18         32495  ...   40  119612   2205             0

차종종별
연료    하이브리드(LPG+전기) 하이브리드(경유+전기) 하이브리드(휘발유+전기)     휘발유 휘발유(무연) 휘발유(유연)
사용본거지
강남구            1262           70        128936  810405  785399     985
강동구             913           12         38780  331844  478959     611
강북구             613           21         14864  164004  268579     283
강서구            1376           27         88857  478932  714384     952
관악구            1338           18         32495  289618  446396     613

[5 rows x 52 columns]

## 3. 파일 저장

In [189]:
# 전체 19년 데이터
import json
df_19.to_json("total_car19.json", orient = 'columns')
# 차종별 20년 데이터
df_19_type.to_json("type_car19.json", orient = 'columns')

In [190]:
# 값 확인
df_read_19 = pd.read_json('total_car19.json')
df_read_19.head()

,CNG,경유,기타연료,수소,엘피지,전기,하이브리드(CNG+전기),하이브리드(LPG+전기),하이브리드(경유+전기),하이브리드(휘발유+전기),휘발유,휘발유(무연),휘발유(유연)
강남구,2268,2522728,664,1700,497240,231756,0,5048,280,515744,3241620,3141596,3940
강동구,1784,1519864,268,304,620700,11552,0,3652,48,155120,1327376,1915836,2444
강북구,656,877164,48,84,366020,5632,0,2452,84,59456,656016,1074316,1132
강서구,2032,2266156,188,380,947224,16116,0,5504,108,355428,1915728,2857536,3808
관악구,1116,1386844,0,160,478448,8820,0,5352,72,129980,1158472,1785584,2452

In [191]:
df_read_t19 = pd.read_json('type_car19.json')
df_read_t19.head()

,"('승용', 'CNG')","('승용', '경유')","('승용', '기타연료')","('승용', '수소')","('승용', '엘피지')","('승용', '전기')","('승용', '하이브리드(CNG+전기)')","('승용', '하이브리드(LPG+전기)')","('승용', '하이브리드(경유+전기)')","('승용', '하이브리드(휘발유+전기)')",...,"('화물', '수소')","('화물', '엘피지')","('화물', '전기')","('화물', '하이브리드(CNG+전기)')","('화물', '하이브리드(LPG+전기)')","('화물', '하이브리드(경유+전기)')","('화물', '하이브리드(휘발유+전기)')","('화물', '휘발유')","('화물', '휘발유(무연)')","('화물', '휘발유(유연)')"
강남구,567,630682,166,425,124310,57939,0,1262,70,128936,...,425,124310,57939,0,1262,70,128936,810405,785399,985
강동구,446,379966,67,76,155175,2888,0,913,12,38780,...,76,155175,2888,0,913,12,38780,331844,478959,611
강북구,164,219291,12,21,91505,1408,0,613,21,14864,...,21,91505,1408,0,613,21,14864,164004,268579,283
강서구,508,566539,47,95,236806,4029,0,1376,27,88857,...,95,236806,4029,0,1376,27,88857,478932,714384,952
관악구,279,346711,0,40,119612,2205,0,1338,18,32495,...,40,119612,2205,0,1338,18,32495,289618,446396,613