In [1]:
import pandas as pd
import

In [22]:
data = pd.read_excel("자치구별 연료별 자동차 등록현황.xlsx")
data.head()

,2015년 ~ 2021년도 12월말 기준 시군구별 용도별 차종별 연료별 등록 현황,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,연월,사용본거지시군구,시군구코드,용도,차종종별,연료,건수
1,202012,서울특별시 종로구,11110,관용,승용,휘발유,155
2,202012,서울특별시 종로구,11110,관용,화물,경유,330
3,202012,서울특별시 종로구,11110,관용,화물,기타연료,3
4,202012,서울특별시 종로구,11110,관용,특수,기타연료,2

## 컬럼 및 값 정리

In [23]:
# 컬럼명 변경
data = data.drop(index=0, axis=0)
data.columns = ['등록연도', '사용본거지', '시군구코드', '용도', '차종종별', '연료', '건수']
data.head()

     등록연도      사용본거지  시군구코드   용도 차종종별    연료   건수
1  202012  서울특별시 종로구  11110   관용   승용   휘발유  155
2  202012  서울특별시 종로구  11110   관용   화물    경유  330
3  202012  서울특별시 종로구  11110   관용   화물  기타연료    3
4  202012  서울특별시 종로구  11110   관용   특수  기타연료    2
5  202012  서울특별시 종로구  11110  자가용   화물   휘발유   71

In [24]:
# 등록연도 값 정리 (년도만 출력)
for i in range(3077):
    data.iloc[i, 0] = data.iloc[i, 0][:4]
    
data['등록연도']

1       2020
2       2020
3       2020
4       2020
5       2020
        ...
3073    2021
3074    2021
3075    2021
3076    2021
3077    2021
Name: 등록연도, Length: 3077, dtype: object

In [29]:
## 값 확인하기
print("****null값****", '\n', data.isnull().sum(), '\n')
print("****사용본거지****", '\n', data['사용본거지'].value_counts(), '\n')
print("****시군구코드****", '\n', data['시군구코드'].value_counts(), '\n')
print("****용도****", '\n', data['용도'].value_counts(), '\n')
print("****차종종별", '\n', data['차종종별'].value_counts(),'\n')
print("****연료", '\n', data["연료"].value_counts())

****null값****
 등록연도     0
사용본거지    0
시군구코드    0
용도       0
차종종별     0
연료       0
건수       0
dtype: int64

****사용본거지****
 서울특별시 서초구     136
서울특별시 성동구     134
서울특별시 송파구     132
서울특별시 영등포구    132
서울특별시 강서구     131
서울특별시 강남구     130
서울특별시 종로구     127
서울특별시 마포구     127
서울특별시 중구      125
서울특별시 서대문구    123
서울특별시 도봉구     123
서울특별시 은평구     122
서울특별시 양천구     122
서울특별시 중랑구     121
서울특별시 광진구     121
서울특별시 노원구     120
서울특별시 구로구     119
서울특별시 금천구     119
서울특별시 강동구     119
서울특별시 동대문구    118
서울특별시 강북구     117
서울특별시 성북구     117
서울특별시 관악구     115
서울특별시 용산구     115
서울특별시 동작구     112
Name: 사용본거지, dtype: int64

****시군구코드****
 11650    136
11200    134
11710    132
11560    132
11500    131
11680    130
11110    127
11440    127
11140    125
11410    123
11320    123
11380    122
11470    122
11260    121
11215    121
11350    120
11530    119
11545    119
11740    119
11230    118
11305    117
11290    117
11620    115
11170    115
11590    112
Name: 시군구코드, dtype: int64

****용도****
 자가용    1399
영업용     866
관용      812
Name: 용도, dtype: int64

****차종종별
 승용    1336
화물     764
승합     663
특수     314
Name: 차종종별, dtype: int64

****연료
 경유               600
엘피지              479
전기               360
기타연료             294
휘발유(무연)          282
휘발유              281
CNG              260
하이브리드(휘발유+전기)    153
하이브리드(LPG+전기)    112
수소               107
하이브리드(경유+전기)      80
휘발유(유연)           55
하이브리드(CNG+전기)     14
Name: 연료, dtype: int64

In [ ]:
data1 = data[data[]]

In [ ]:
# 연료별로 묶기
pd.pivot_table(data,
              index = ["연료", "등록연도"],
              columns = "",
              values = "건수",
              aggfunc = 'sum')