In [1]:
import pandas as pd

In [2]:
data = pd.read_excel("자치구별 연료별 자동차 등록현황.xlsx")
data.head()

,2015년 ~ 2021년도 12월말 기준 시군구별 용도별 차종별 연료별 등록 현황,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,연월,사용본거지시군구,시군구코드,용도,차종종별,연료,건수
1,202012,서울특별시 종로구,11110,관용,승용,휘발유,155
2,202012,서울특별시 종로구,11110,관용,화물,경유,330
3,202012,서울특별시 종로구,11110,관용,화물,기타연료,3
4,202012,서울특별시 종로구,11110,관용,특수,기타연료,2

## 컬럼 및 값 정리

In [3]:
# 컬럼명 변경
data = data.drop(index=0, axis=0)
data.columns = ['등록연도', '사용본거지', '시군구코드', '용도', '차종종별', '연료', '건수']
data.head()

     등록연도      사용본거지  시군구코드   용도 차종종별    연료   건수
1  202012  서울특별시 종로구  11110   관용   승용   휘발유  155
2  202012  서울특별시 종로구  11110   관용   화물    경유  330
3  202012  서울특별시 종로구  11110   관용   화물  기타연료    3
4  202012  서울특별시 종로구  11110   관용   특수  기타연료    2
5  202012  서울특별시 종로구  11110  자가용   화물   휘발유   71

In [19]:
# 등록연도 값 정리 (년도만 출력)
for i in range(3077):
    data.iloc[i, 0] = int(data.iloc[i, 0][:4])
    
data['등록연도']

1       2020
2       2020
3       2020
4       2020
5       2020
        ...
3073    2021
3074    2021
3075    2021
3076    2021
3077    2021
Name: 등록연도, Length: 3077, dtype: object

In [20]:
## 값 확인하기
print("****null값****", '\n', data.isnull().sum(), '\n')
print("****사용본거지****", '\n', data['사용본거지'].value_counts(), '\n')
print("****시군구코드****", '\n', data['시군구코드'].value_counts(), '\n')
print("****용도****", '\n', data['용도'].value_counts(), '\n')
print("****차종종별", '\n', data['차종종별'].value_counts(),'\n')
print("****연료", '\n', data["연료"].value_counts())

****null값****
 등록연도     0
사용본거지    0
시군구코드    0
용도       0
차종종별     0
연료       0
건수       0
dtype: int64

****사용본거지****
 서울특별시 서초구     136
서울특별시 성동구     134
서울특별시 송파구     132
서울특별시 영등포구    132
서울특별시 강서구     131
서울특별시 강남구     130
서울특별시 종로구     127
서울특별시 마포구     127
서울특별시 중구      125
서울특별시 서대문구    123
서울특별시 도봉구     123
서울특별시 은평구     122
서울특별시 양천구     122
서울특별시 중랑구     121
서울특별시 광진구     121
서울특별시 노원구     120
서울특별시 구로구     119
서울특별시 금천구     119
서울특별시 강동구     119
서울특별시 동대문구    118
서울특별시 강북구     117
서울특별시 성북구     117
서울특별시 관악구     115
서울특별시 용산구     115
서울특별시 동작구     112
Name: 사용본거지, dtype: int64

****시군구코드****
 11650    136
11200    134
11710    132
11560    132
11500    131
11680    130
11110    127
11440    127
11140    125
11410    123
11320    123
11380    122
11470    122
11260    121
11215    121
11350    120
11530    119
11545    119
11740    119
11230    118
11305    117
11290    117
11620    115
11170    115
11590    112
Name: 시군구코드, dtype: int64

****용도****
 자가용    1399
영업용     866
관용      812
Name: 용도, dtype: int64

****차종종별
 승용    1336
화물     764
승합     663
특수     314
Name: 차종종별, dtype: int64

****연료
 경유               600
엘피지              479
전기               360
기타연료             294
휘발유(무연)          282
휘발유              281
CNG              260
하이브리드(휘발유+전기)    153
하이브리드(LPG+전기)    112
수소               107
하이브리드(경유+전기)      80
휘발유(유연)           55
하이브리드(CNG+전기)     14
Name: 연료, dtype: int64

In [39]:
# 문자 값 변경 방법: 인코딩 -LabelEncoder
#각 값 객체의 개수에 따라 입력해서 바꿔줌(0, 1 로 2개면 2개, 1,2,3으로 3개면 3개)
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder() #객체를 만들어줌
features = ['차종종별', '용도'] #바꿀 열 따로  뽑아줌(for 문 사용하기 위해)
for f in features:
    data[f] = le.fit_transform(data[f])  #fit _ transform
data.head()

   등록연도      사용본거지  시군구코드  용도  차종종별    연료   건수
1  2020  서울특별시 종로구  11110   0     0   휘발유  155
2  2020  서울특별시 종로구  11110   0     3    경유  330
3  2020  서울특별시 종로구  11110   0     3  기타연료    3
4  2020  서울특별시 종로구  11110   0     2  기타연료    2
5  2020  서울특별시 종로구  11110   2     3   휘발유   71

In [41]:
print(data['차종종별'].value_counts(), '\n')
data['용도'].value_counts()

0    1336
3     764
1     663
2     314
Name: 차종종별, dtype: int64

2    1399
1     866
0     812
Name: 용도, dtype: int64

# 해야 할 부분
년도별로 나누기
지역별로 합치기
연료별로 합치기

In [42]:
# 빈데이터프레임 생성
df = pd.DataFrame(columns=['년도', '주소', '용도', '연료', '건수'])
df

Empty DataFrame
Columns: [년도, 주소, 용도, 연료, 건수]
Index: []

In [43]:
# 연료별로 묶기 

# 2020년도
# 20년도 전기가 아니것 
df1 = data[(data['등록연도'] == 2020) & (data['연료']!="전기")]

# 20년도 전기가 아닌것
df2 = data[(data['등록연도'] == 2020) & (data['연료']=="전기")]

In [44]:
# 전기가 아닌것
df1

      등록연도      사용본거지  시군구코드  용도  차종종별       연료     건수
1     2020  서울특별시 종로구  11110   0     0      휘발유    155
2     2020  서울특별시 종로구  11110   0     3       경유    330
3     2020  서울특별시 종로구  11110   0     3     기타연료      3
4     2020  서울특별시 종로구  11110   0     2     기타연료      2
5     2020  서울특별시 종로구  11110   2     3      휘발유     71
...    ...        ...    ...  ..   ...      ...    ...
1600  2020  서울특별시 강동구  11740   1     3       경유   2077
1680  2020  서울특별시 강동구  11740   2     1     기타연료     68
1681  2020  서울특별시 강동구  11740   2     3       경유  11506
1682  2020  서울특별시 강동구  11740   1     2       경유    228
1734  2020  서울특별시 강동구  11740   1     0  휘발유(무연)    245

[1353 rows x 7 columns]

In [45]:
# 전기차일 때 
df2

      등록연도      사용본거지  시군구코드  용도  차종종별  연료   건수
8     2020  서울특별시 종로구  11110   1     0  전기    5
12    2020   서울특별시 중구  11140   0     0  전기  124
19    2020  서울특별시 용산구  11170   2     0  전기  412
23    2020  서울특별시 용산구  11170   1     0  전기    2
49    2020  서울특별시 성동구  11200   2     0  전기  362
...    ...        ...    ...  ..   ...  ..  ...
1483  2020  서울특별시 송파구  11710   1     0  전기   81
1555  2020  서울특별시 강남구  11680   1     3  전기   24
1557  2020  서울특별시 송파구  11710   0     0  전기   47
1565  2020  서울특별시 강동구  11740   0     0  전기   43
1581  2020  서울특별시 강동구  11740   2     0  전기  408

[166 rows x 7 columns]

In [48]:
# 20년도 전기가 아니것 지역별로 묶기

df_1 = pd.pivot_table(df1,
                     values = '건수',
                     index = '사용본거지',
                     columns = '연료',
                     aggfunc = 'sum')
df_1

연료,CNG,경유,기타연료,수소,엘피지,하이브리드(CNG+전기),하이브리드(LPG+전기),하이브리드(경유+전기),하이브리드(휘발유+전기),휘발유,휘발유(무연),휘발유(유연)
사용본거지,,,,,,,,,,,,
서울특별시 강남구,274.0,69776.0,616.0,129.0,11306.0,NaN,86.0,156.0,13520.0,66858.0,65913.0,87.0
서울특별시 강동구,235.0,52165.0,292.0,132.0,14770.0,2.0,68.0,40.0,5377.0,30088.0,45991.0,57.0
서울특별시 강북구,675.0,27997.0,97.0,16.0,8209.0,NaN,42.0,10.0,1776.0,13437.0,23102.0,20.0
서울특별시 강서구,411.0,70983.0,316.0,88.0,20939.0,NaN,105.0,49.0,9749.0,39237.0,62296.0,76.0
서울특별시 관악구,245.0,42162.0,146.0,45.0,11063.0,NaN,100.0,16.0,3668.0,23130.0,38361.0,45.0
서울특별시 광진구,191.0,36890.0,146.0,30.0,7922.0,NaN,53.0,47.0,3004.0,20568.0,29694.0,34.0
서울특별시 구로구,374.0,55409.0,282.0,143.0,13998.0,NaN,105.0,17.0,4107.0,25434.0,44404.0,50.0
서울특별시 금천구,398.0,36629.0,148.0,20.0,7489.0,NaN,89.0,18.0,2251.0,14266.0,26605.0,43.0
서울특별시 노원구,608.0,50741.0,259.0,33.0,17182.0,31.0,102.0,24.0,4492.0,28904.0,49810.0,48.0
서울특별시 도봉구,354.0,34019.0,145.0,23.0,11755.0,8.0,59.0,21.0,2249.0,17103.0,29721.0,35.0
서울특별시 동대문구,54.0,37125.0,188.0,37.0,8753.0,NaN,50.0,29.0,2694.0,19350.0,29406.0,32.0
서울특별시 동작구,65.0,35112.0,120.0,67.0,7480.0,NaN,71.0,31.0,3959.0,23568.0,34689.0,36.0
서울특별시 마포구,325.0,41768.0,261.0,96.0,8231.0,NaN,59.0,40.0,4411.0,26959.0,36640.0,32.0
서울특별시 서대문구,284.0,30408.0,162.0,63.0,7851.0,2.0,56.0,21.0,3086.0,18854.0,28315.0,36.0
서울특별시 서초구,538.0,58746.0,404.0,158.0,7503.0,NaN,65.0,75.0,8228.0,50897.0,52313.0,68.0
서울특별시 성동구,464.0,37886.0,190.0,34.0,8190.0,NaN,77.0,52.0,3441.0,21979.0,32765.0,37.0
서울특별시 성북구,743.0,42296.0,216.0,35.0,9555.0,3.0,57.0,32.0,3732.0,24686.0,38342.0,42.0
서울특별시 송파구,834.0,87498.0,488.0,116.0,16788.0,4.0,129.0,94.0,9391.0,56439.0,72875.0,102.0
서울특별시 양천구,618.0,51508.0,297.0,59.0,13921.0,NaN,98.0,30.0,4912.0,32709.0,46698.0,42.0
서울특별시 영등포구,115.0,55172.0,433.0,110.0,9799.0,NaN,105.0,40.0,5250.0,29655.0,43493.0,57.0
서울특별시 용산구,28.0,26069.0,261.0,44.0,3653.0,NaN,26.0,25.0,3049.0,23281.0,22059.0,21.0
서울특별시 은평구,746.0,45175.0,196.0,81.0,12851.0,1.0,96.0,18.0,3889.0,26376.0,42231.0,46.0
서울특별시 종로구,124.0,18504.0,181.0,52.0,2421.0,NaN,29.0,16.0,1844.0,11285.0,15526.0,7.0
서울특별시 중구,34.0,20600.0,286.0,32.0,3061.0,NaN,24.0,29.0,1819.0,11217.0,13298.0,12.0
서울특별시 중랑구,377.0,43649.0,175.0,28.0,13754.0,NaN,61.0,20.0,2569.0,19302.0,33641.0,32.0

In [ ]:
# 지역별로 종류별 그래프 출력 (전기차와 그게 아닌것으로 구분되게끔)